In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('/content/Salaries.csv')

In [8]:

data.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

Total category rank

In [20]:
cat=data.groupby('rank').count()
print(cat)

           discipline  phd  service  sex  salary
rank
AssocProf          13   13       13   13      13
AsstProf           19   19       19   19      19
Prof               46   46       46   46      46

total no of gender count on the base of rank

In [18]:
cat=data.groupby('rank')['sex'].value_counts()
print(cat)

rank       sex
AssocProf  Female    10
           Male       3
AsstProf   Female    11
           Male       8
Prof       Male      28
           Female    18
Name: count, dtype: int64

Max Salary of each rank

In [23]:
cat=data.groupby('rank')['salary'].max()
cat

rank
AssocProf    119800
AsstProf      97032
Prof         186960
Name: salary, dtype: int64

calculating mean of each rank salaries

In [27]:
cat=data.groupby('rank')['salary'].mean()
cat

rank
AssocProf     91786.230769
AsstProf      81362.789474
Prof         123624.804348
Name: salary, dtype: float64

only show me columns where salary is greater then 120000

In [49]:
cat=data[data['salary']>120000].shape[0]
print(cat)

25

only show me data of females

In [31]:
cat=data[data['sex']=='Female']
print(cat)

         rank discipline  phd  service     sex  salary
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

select data of first 10 rows

In [32]:
data[:10]

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

give me first 10 rows with features rank,sex,salary

In [33]:
cat=data[['rank','sex','salary']][:10]
print(cat)

        rank   sex  salary
0       Prof  Male  186960
1       Prof  Male   93000
2       Prof  Male  110515
3       Prof  Male  131205
4       Prof  Male  104800
5       Prof  Male  122400
6  AssocProf  Male   81285
7       Prof  Male  126300
8       Prof  Male   94350
9       Prof  Male   57800

In [37]:
cat=data.loc[:10,['rank','sex','salary']]
print(cat)

         rank   sex  salary
0        Prof  Male  186960
1        Prof  Male   93000
2        Prof  Male  110515
3        Prof  Male  131205
4        Prof  Male  104800
5        Prof  Male  122400
6   AssocProf  Male   81285
7        Prof  Male  126300
8        Prof  Male   94350
9        Prof  Male   57800
10       Prof  Male  128250

In [38]:
cat=data.iloc[:10,[0,1,2]]
print(cat)

        rank discipline  phd
0       Prof          B   56
1       Prof          A   12
2       Prof          A   23
3       Prof          A   40
4       Prof          B   20
5       Prof          A   20
6  AssocProf          A   20
7       Prof          A   18
8       Prof          A   29
9       Prof          A   51

In [41]:
cat=data.iloc[0:5,[0,1,2]]
print(cat)

   rank discipline  phd
0  Prof          B   56
1  Prof          A   12
2  Prof          A   23
3  Prof          A   40
4  Prof          B   20

sorting values by service

In [42]:
data.sort_values(by='service')

        rank discipline  phd  service     sex  salary
55  AsstProf          A    2        0  Female   72500
23  AsstProf          A    2        0    Male   85000
43  AsstProf          B    5        0  Female   77000
17  AsstProf          B    4        0    Male   92000
12  AsstProf          B    1        0    Male   88000
..       ...        ...  ...      ...     ...     ...
40      Prof          A   39       36  Female  137000
27      Prof          A   45       43    Male  155865
36      Prof          B   45       45    Male  146856
0       Prof          B   56       49    Male  186960
9       Prof          A   51       51    Male   57800

[78 rows x 6 columns]

sorting on the basis of salary and sevice

In [45]:
data.sort_values(by=['service','salary'],ascending=[True,False])

        rank discipline  phd  service     sex  salary
52      Prof          A   12        0  Female  105000
17  AsstProf          B    4        0    Male   92000
12  AsstProf          B    1        0    Male   88000
23  AsstProf          A    2        0    Male   85000
43  AsstProf          B    5        0  Female   77000
..       ...        ...  ...      ...     ...     ...
40      Prof          A   39       36  Female  137000
27      Prof          A   45       43    Male  155865
36      Prof          B   45       45    Male  146856
0       Prof          B   56       49    Male  186960
9       Prof          A   51       51    Male   57800

[78 rows x 6 columns]

checking that there is any null value in the data

In [46]:
data[data.isnull().any(axis=1)]

Empty DataFrame
Columns: [rank, discipline, phd, service, sex, salary]
Index: []